- name: software | repo | add 1password repo key (debian)
  become: yes
  apt_key:
    url: https://downloads.1password.com/linux/keys/1password.asc
    state: present
  when: has_apt

- name: software | repo | 1password (debian)
  become: yes
  tags: packages,repo
  apt_repository:
    repo: deb [arch=amd64 signed-by=/usr/share/keyrings/1password-archive-keyring.gpg] https://downloads.1password.com/linux/debian/amd64 stable main
    filename: /etc/apt/sources.list.d/1password.list
  register: one_password_repo
  when: has_apt

- name: software | repo | add 1password repo key (fedora)
  become: yes
  copy:
    src: software/dnf_repos/1password.repo
    dest: /etc/yum.repos.d/1password.repo
    owner: root
    group: root
    mode: 0600
  when: has_dnf

- name: sofware | repo | check for 1password gpg (arch)
  command: gpg --list-keys 3FEF9748469ADBE15DA7CA80AC2D62742012EA22
  register: gpg_1password_key
  when: has_pacman

# - block:
#     - name: software | repo | get 1password asc
#       uri:
#         uri: https://downloads.1password.com/linux/keys/1password.asc
#         return_content: yes
#       register: one_password_asc

#     - name: software | repo | add 1password gpg
#       command: gpg --import {{ one_password_asc.content }}

#     - name: software | download 1password (arch)
#       git:
#         repo: https://aur.archlinux.org/1password.git
#         dest: /tmp/1password
#         depth: 1
#         version: master

#     - name: software | build 1password (arch)
#       command: makepkg -si /tmp/1password

#   when: has_pacman and gpg_1password_key.rc != 0
