- name: Load distro specific variables
  include_vars: "{{ ansible_facts.os_family }}.yml"
  tags: always

- name: utilities | install packages
  tags: packages,system,settings
  become: true
  package:
    state: present
    name:
      - automake
      - autoconf
      - curl
      - fish
      - htop
      - jq
      - libncurses5-dev
      - libssl-dev
      - neofetch
      - "{{ python_pip_package }}"
      - rcm
      - tmux
      - vim

- name: utilities | install pip packages
  tags: packages,system,settings
  pip:
    name:
      - psutil 
- name: utilities | check starship
  stat:
    path: "/usr/local/bin/starship"
  register: starship_command

- name: utilities | install starship
  tags: packages,system,starship
  command: sh -c "$(curl -fsSL https://starship.rs/install.sh)"
  when: not starship_command.stat.exists

- name: utilities | install man-pages (arch)
  tags: packages,system,settings
  pacman:
    state: present
    name:
      - man-db
      - man-pages
  when: has_pacman

- name: save user as fact
  set_fact:
    the_user: "{{ ansible_user_id }}"

- name: change user shell to fish
  become: yes
  user:
    name: "{{ the_user }}"
    shell: /usr/bin/fish

- import_tasks: ssh_config.yml
  tags: ssh

- import_tasks: gpg_config.yml
  tags: gpg

- import_tasks: dotfiles.yml
  tags: dotfiles

- import_tasks: asdf.yml
  tags: asdf

- import_tasks: gnome/keybindings.yml
  tags: gnome,keybindings

- import_tasks: gnome/peripherals.yml
  tags: gnome,peripherals

- import_tasks: gnome/shell.yml
  tags: gnome,shell

- import_tasks: gnome/terminal.yml
  tags: gnome,terminal

- name: "gnome | extensions | install extensions"
  include_role:
    name: jaredhocutt.gnome_extensions

- name: "gnome | fonts | install nerd fonts"
  tags: fonts
  include_role:
    name: ctorgalson.nerdfonts

- name: copy profile image
  become: yes
  copy:
    src: profile_image.jpg
    dest: /var/lib/AccountsService/icons/eric
    owner: root
    group: root
    mode: 0644

- import_tasks: software/main.yml
  tags: software
# install protonmail bridge
