- name: dotfiles | ensure github.com is a known host
  lineinfile:
    dest: ~/.ssh/known_hosts
    create: yes
    state: present
    line: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
    regexp: "^github\\.com"
    mode: 0600

- name: dotfiles | clone dotfiles
  git:
    repo: git@github.com:enewbury/dotfiles.git
    dest: "{{ dotfiles_dir }}"
    update: false
    version: "main"

- name: dotfiles | clone tpm
  git:
    repo: https://github.com/tmux-plugins/tpm.git
    dest: ~/.tmux/plugins/tpm
    depth: 1
    version: v3.0.0

- name: dotfiles | ensure .local directory exists
  file:
    path: ~/.local
    state: directory
    mode: 0700

- name: dotfiles | check for local fish file
  stat:
    path: ~/.local/local.fish
  register: local_fish_file

- block:
    - name: dotfiles | lookup local fish config
      command: op document get "local.fish"
      register: local_fish

    - name: dotfiles | copy local fish config
      copy:
        content: "{{ local_fish.stdout }}"
        dest: ~/.local/local.fish
        mode: 0644
  when: not local_fish_file.stat.exists

- name: dotfiles | check for local gitconfig
  stat:
    path: ~/.local/gitconfig
  register: local_gitconfig_file

- block:
    - name: dotfiles | lookup local git config
      command: op document get "gitconfig.local"
      register: local_gitconfig

    - name: dotfiles | copy local git config
      copy:
        content: "{{ local_gitconfig.stdout }}"
        dest: ~/.local/gitconfig
        mode: 0644
  when: not local_gitconfig_file.stat.exists

- name: dotfiles | check for local hex config
  stat:
    path: ~/.hex/hex.config
  register: local_hex_file

- block:
    - name: dotfiles | lookup hex config
      command: op document get "hex.config"
      register: hex_config

    - name: dotfiles | ensure hex directory exists
      file:
        path: ~/.hex
        state: directory
        mode: 0755

    - name: dotfiles | copy hex config
      copy:
        content: "{{ hex_config.stdout }}"
        dest: ~/.hex/hex.config
        mode: 0644
  when: not local_hex_file.stat.exists

- name: dotfiles | setup dotfiles
  command: rcup -d {{ dotfiles_dir  }}
  environment:
    RCRC: "{{ dotfiles_dir }}/rcrc"
  changed_when: false

- name: dotfiles | make the fisher directory
  file:
    path: "~/.config/fish/functions"
    state: directory
    mode: 0755
    recurse: yes

- name: dotfiles | install fisher
  get_url:
    url: https://git.io/fisher
    dest: "~/.config/fish/functions/fisher.fish"

- name: dotfiles | install fisher plugins
  command: fish -c "fisher update"
  changed_when: false
