- name: gpg config | lookup public key key_id
  command: op item get "public.gpg" --fields label=key_id
  register: gpg_key_id
  changed_when: false

- name: gpg config | check if key exists
  command: gpg --list-secret-keys {{ gpg_key_id.stdout_lines[0] }}
  register: gpg_key_list
  failed_when: false
  changed_when: false

- block:
    - name: gpg config | lookup public key document
      command: op document get "public.gpg"
      register: gpg_pub_doc

    - name: gpg config | import public key
      shell: echo "{{ gpg_pub_doc.stdout }}" | gpg --import

    - name: gpg config | load private key
      command: op document get "private.gpg"
      register: gpg_sec_doc

    - name: gpg config | import private key
      shell: echo "{{ gpg_sec_doc.stdout }}" | gpg --allow-secret-key-import --import --batch

    - name: gpg_config | set trust to ultimate
      shell: echo "{{ gpg_key_id.stdout_lines[0] }}:6" | gpg --import-ownertrust


    - block:
      - name: gpg config | add gpg-agent.conf
        shell: echo "pinentry-program $(brew --prefix)/bin/pinentry-mac" > ~/.gnupg/gpg-agent.conf

      - name: gpg config | update gpg.conf
        copy:
          dest: ~/.gnupg/gpg.conf
          content: use-agent

      - name: gpg config | restart agent
        command: killall gpg-agent

      when: ansible_facts.os_family == "Darwin"
  when: gpg_key_list.rc != 0
