- name: gpg config | lookup public key key_id
  command: op item get "public.gpg" --fields label=key_id
  register: gpg_key_id
  changed_when: false

- name: gpg config | check if key exists
  command: gpg --list-secret-keys {{ gpg_key_id.stdout_lines[0] }}
  register: gpg_key_list
  failed_when: false
  changed_when: false

- block:
    - name: gpg config | lookup public key document
      command: op document get "public.gpg"
      register: gpg_pub_doc

    - name: gpg config | import public key
      shell: echo "{{ gpg_pub_doc.stdout }}" | gpg --import

    - name: gpg config | load private key
      command: op document get "private.gpg"
      register: gpg_sec_doc

    - name: gpg config | import private key
      shell: echo "{{ gpg_sec_doc.stdout }}" | gpg --allow-secret-key-import --import --batch

    - name: gpg_config | set trust to ultimate
      shell: echo "{{ gpg_key_id.stdout_lines[0] }}:6" | gpg --import-ownertrust
  when: gpg_key_list.rc != 0
