- name: Load distro specific variables
  include_vars: "{{ ansible_facts.os_family }}.yml"
  tags: always

- block:
  - import_tasks: repositories/main.yml
  tags: repositories

- block:
  - import_tasks: utilities.yml
  tags: utilities

- block:
  - import_tasks: shell.yml
  tags: shell

- block:
  - import_tasks: ssh_config.yml
  tags: ssh

- block:
  - import_tasks: gpg_config.yml
  tags: gpg

- block:
  - import_tasks: dotfiles.yml
  tags: dotfiles

- block: 
  - import_tasks: asdf.yml
  tags: asdf

- block:
  - import_tasks: software/main.yml
  tags: software

- block:
  - import_tasks: theming.yml
  tags: theming

- block:
  - import_tasks: gnome/main.yml
  when: ansible_facts.os_family != "Darwin"
  tags: gnome

- block:
  - import_tasks: fonts.yml
  tags: fonts
