- name: ssh config | ensure .ssh directory exists
  file:
    path: ~/.ssh
    state: directory
    mode: 0700

- name: ssh config | check for public key file
  stat:
    path: ~/.ssh/id_ed25519.pub
  register: id_ed25519_pub_stat

- block:
    - name: ssh config | lookup public key from 1password
      onepassword_info:
        search_terms:
          - name: "id_ed25519.pub"
        auto_login: "{{ op_login }}"
      register: id_ed25519_pub_info

    - name: set public key item fact
      set_fact:
        pub_item: "{{ id_ed25519_pub_info['onepassword']['id_ed25519.pub'] }}"

    - name: ssh config | copy public key
      copy:
        content: "{{ pub_item['document'] }}\n"
        dest: ~/.ssh/id_ed25519.pub
        mode: 0644

  when: not id_ed25519_pub_stat.stat.exists

- name: ssh config | check for private key file
  stat:
    path: ~/.ssh/id_ed25519
  register: id_ed25519_stat

- block:
    - name: ssh config | lookup private key from 1password
      onepassword_info:
        search_terms:
          - name: "id_ed25519"
        auto_login: "{{ op_login }}"
      register: id_ed25519_info

    - name: set private key item fact
      set_fact:
        priv_item: "{{ id_ed25519_info['onepassword']['id_ed25519'] }}"

    - name: ssh config | copy public key
      copy:
        content: "{{ priv_item['document'] }}\n"
        dest: ~/.ssh/id_ed25519
        mode: 0600

    - name: ssh config | start ssh-agent
      command: ssh-agent

    - name: ssh config | add key to agent
      command: ssh-add ~/.ssh/id_ed25519
      environment:
        SSH_ASKPASS: ""
  when: not id_ed25519_stat.stat.exists
