- name: ssh config | ensure .ssh directory exists
  file:
    path: ~/.ssh
    state: directory
    mode: 0700

- name: ssh config | check for public key file
  stat:
    path: ~/.ssh/id_ed25519.pub
  register: id_ed25519_pub_stat

- block:
    - name: ssh config | lookup public key from 1password
      command: op document get "id_ed25519.pub"
      register: id_ed25519_pub

    - name: ssh config | copy public key
      copy:
        content: "{{ id_ed25519_pub.stdout }}"
        dest: ~/.ssh/id_ed25519.pub
        mode: 0644
  when: not id_ed25519_pub_stat.stat.exists

- name: ssh config | check for private key file
  stat:
    path: ~/.ssh/id_ed25519
  register: id_ed25519_stat

- block:
    - name: ssh config | lookup private key from 1password
      command: op document get "id_ed25519"
      register: id_ed25519

    - name: ssh config | copy public key
      copy:
        content: "{{ id_ed25519.stdout }}\n"
        dest: ~/.ssh/id_ed25519
        mode: 0600

    - name: ssh config | start ssh-agent
      command: ssh-agent

    - name: ssh config | add key to agent
      command: ssh-add ~/.ssh/id_ed25519
      environment:
        SSH_ASKPASS: ""
  when: not id_ed25519_stat.stat.exists
