
- name: theming | copy profile image
  become: true
  copy:
    src: profile_image.jpg
    dest: /var/lib/AccountsService/icons/eric
    owner: root
    group: root
    mode: 0644
  when: ansible_facts.os_family != "Darwin"
