- name: utilities | install packages
  become: true
  package:
    state: present
    name:
      - 1password-cli
      - automake
      - autoconf
      - curl
      - fish
      - fzf
      - jq
      - libstdc++-static
      - gcc-c++
      - ripgrep
      - neofetch
      - "{{ python_pip_package }}"
      - tmux
      - vim
      - neovim
      - starship
      - rcm
      - ghq
  when: ansible_facts.os_family != "Darwin"

- name: utilities | mac brew packages
  homebrew:
    name: 
      - fish
      - fzf
      - gpg
      - jq
      - mas
      - pinentry-mac
      - neofetch
      - ripgrep
      - tmux
      - vim
      - neovim
      - rcm
      - starship
      - ghq
    state: present
  when: ansible_facts.os_family == "Darwin"

- name: utilities | install pip packages
  pip:
    name:
      - psutil

- name: utilities | install man-pages (arch)
  pacman:
    state: present
    name:
      - man-db
      - man-pages
  when: has_pacman
