- name: software | flatpak | add flatpak support
  become: yes
  package:
    name: flatpak
    state: present

- name: software | flatpak | add flathub remote
  become: yes
  command: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
  changed_when: false

- name: softare | flatpak | install apps
  flatpak:
    name: "{{ item }}"
  with_items:
    - org.gimp.GIMP
    - com.spotify.Client
    - im.riot.Riot
    - org.gnome.Geary
    - us.zoom.Zoom
    - com.slack.Slack
    - com.nextcloud.desktopclient.nextcloud
    - md.obsidian.Obsidian

- import_tasks: "1password.yml"

- name: software | install packages
  become: yes
  package:
    name:
      - "{{ wireguard_name }}"